Imports Controlid
Imports System

Imports System.Text


Public Class Usuario

    'Adiciona usuario
    Shared Function Add_users() As RepCid

        Dim rep As RepCid
        Dim status, gravou As New Boolean


        If rep Is Nothing Then

            rep = New RepCid()

            rep = Conexao.ConectaRep_iDClass()
            'Método GravarUsuario(Long,string,integer,string,string,integer,integer,boolean)
            status = rep.GravarUsuario(85393853933, "Mauro - Teste", 125, "12345", "121", 0, 1, gravou)

            If status = True Then

                Console.WriteLine("Gravou")
                rep.Desconectar()
            Else

                Console.WriteLine("Não gravou")

            End If

        End If

    End Function


    'Extrair o template
    Shared Function Set_template() As RepCid

        Dim rep As RepCid
        Dim status, gravou As New Boolean
        Dim template As String
        Dim pis As Long
        Dim enc As Encoding = New UTF8Encoding(True, True)



        If rep Is Nothing Then

            rep = New RepCid()
            rep = Conexao.ConectaRep_iDClass()
            'Template do Mauro'
            template = "SUNSUzIxAAAH7AMBAAAAAMUAxQDvADoBAAAAglQNcQB1AIgPMQCAAG8PwQCRAKEPJQDKAFgPWgDdAFwPugDeAKkPMgDyAEoPpADyACcOfAD1AJgPigD2AKcPWQD6AEQNrwACAasOagAPASQOcxsH60MvD+tbG0MXJ/tvGy9/XhM7/ksXZRs+x5IXOoQmAkcGQgrq9ybzgX3Vgz6A7fBCdGZVXRDVg+b+YSP96zqtfYWiBmIGAeM2jEJ+LxggLAEBsBU6AwBRO3rBBwCkRRrA/zYDAFJHg8MDAGtNCf4FAJhjHFQEAKFNIl0EAMBsJEUDAFNPgMEHAJNUE/4+/w4AJlr6Qv47TFkTABhs7Sk9NcH/P0MIAG1xjIuGDAB1dhNK/VfAQQgAbXeD/4t8AwAtfnTCEQA1f/o4MMD+/0RKAwAuhHDCFQAMouT/QDFANVT/wcESAAy10/w7MP7///7/RsAPACjH3v8n/f7+/j5cEgAHydf/MP/+/v4wNU8EACDLWn4EACXOVmcVAAjT2sD/M/8p/MD+///AwMBRFAAO2df+wP///cD8LkBUbAcAV95npJYFALziKVkDAB7mVsEJAHryoMPHscPBBQBg8xD9UQ8AifOrwsDExMTEl8FsBgAx9Ux+xAUAXvdD/6YDEFgAScMEEGwAJG8EELMGKcDEFhAUB9PAwv7A/f/9/SP9//9FwVYFEGIKQMSdChCNDqTC/8PIyMLDwhQQHBHGNv/+//z9/SP//sDBfAQQbhEgZAUQaRIww5UWELYonP8v/4zDw8XDwsLAwcLBfhQQvDWa///B/MLAwMHExMWp/5IAEACCaBBeADoAgg92AGMAig82AGsAcA/AAIcApQ8mALkAWQ9aANEAXQ4jANIAUg+5ANMArQ+MAOoAqg97AOwAmg5bAPMARQ2rAPwAsg9tAAMBJg2QAAUBpA8dAAcBRw+zABgBpQ8r+FsXG9+jCHMfC+fv8w/rWxsj+28fM/9tCjv+bxdiGULHVzn1+ncNL/Yi/0MFMwtREBEL7vnh8D13CvhZIjas+ulBEwUPZgn54jGPXoWZ/9H3ggz/9S8H//OR93ICg//WJSArAQGgFVQFAD4w/f79xAcAqDcnwj7/BgA9Qv3+wi0HAIRMGsDAPgcApEkgUzEHAJdOGj0wDgAhU/Aqw/z/RsA4AwC8iyT+CABzX4+LgAkAemQT/0tECQByZYmBdcMEADJpd8PBEAA6avr/Nf81RlUDADNvccEXAAqW0Po+K/1BS0Ra/xMABqvW//7+OzUxOEcPACm14v7A/P/9/f/9wP//TgUAIbpcwsDABQAmvVfAcxMAA77TNTMzMf/+UxgAB8bWwP41/yr9///+VMH9g8ATACXO1zT/If3/Nl9XBwBW0mTEkMIFAB7WU2cFACTWUMBZBAC81zB3GQAD38//NcD+/i79//7//sH/wMD/wsHCEQCN5q15wsTFl2d3BQCp5zBxBwAw6ElxwcYQAIforcLBw8TGoH7CwcMJAHnppMPHx8TBiQQAaOweSgcAju4tfHAEAFf2SZUDAFz5ScMFAG37JGgREJEBqcFmxsOxd8LBwgoQjAWiasnJwZ0DEG0HJ8IXELAWp0f+iI/CxcGQwcD/fgQQfimcJAYAYvtJxcKQACAAgwIajAAhAI4OqwBDAIgPaQBPAG4PRABnAOkPQABzAFwPWQCfAFgPjwC0AFwPVgC5AFMPYgDIAE0P2wDLADEOwQDQAK0PsADSAJwOigDYAEQOmgDcAC4OjwDkADsO5QDlALIOxwDpAKcPnADrACkOTQDuAEcP5QD/AKgPiQADAb8OPgAKAUUOfgAMASsO5AAbAZEPawAmAaoOfQAvAagPFwhPI1enm/xzH2+jfod3Fu/j5I+Cf8uT8HdTBQvybQdiD9f9ahlaMkbDUQnx/3cO2f3u90YLyYeBg6qNURAJC81/4fBVckJ0bAtJGF0fufSNBN3s9PstDFkUEQ+Bg0oMkf/W9HoM7fAR/PnnjgQO/wP2mfsZG3IBJZSemIqEEgBTnT8fOWyygJqFseuz4pvv6QWygLfsbQGafafot+fiAiAtAQHAFeMDAJAhBv4FAIgjgHcGALUpF8BGCgCoP4zBwsDCwcGLDwBEQOn//v/+PcAyOwsAp0WGccL/k8AHAK9FEEAwBgBlTXSW/wwAbU76wP1POzwDAGZTcMIQAERv7cL9PDz/NTgDADx0YsEEAEF3WmUOAF2b4DP9//z+/zHBBwBVoFzBZMEJAFqjV8BiwMHAFQApqdNDKcD9OzM4QxUA6a+rwMHAiIzCg8LC/8FkEwBYtdYw/v78/f3/Nf/BwVcIAIy2Z8XBecEHAFG8VmtTCABXvVPAaG0LAGTE0Cr9/PspCgCXxRY2U3kGAI/IV8GfCgBey1CE/8TElQgAZMxMccGfCgCuzqTDx8fDwsKCEgC9zq3BwcTDxsPCw8HC/8HBw4kYACPT00r//8H+/jv//f7+//7B/v/B/QMAn9MiwAMAt+4c/wYAw9MwhMEYACjW18DAVEH//ir+/f/A/1H/BACK20nCwQUAnt0ncA8AxOWpScPExcWdwIkFAI3nQMGXBACT50CdBgCa7jTDkAQQxx8JZQcAoO4kwf+dBwBN9UzCw8bBwRcA4/ypT8DAw4bGwZ7CwcD/wk4DEEYkHsFEQgEBAAAAFgAAAAACBQAAAAAAAEVCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
            pis = 12554275469

            If rep.GravarTemplateUsuarioStr(pis, template, gravou) = True Then

                Console.WriteLine("Gravou")
                rep.Desconectar()

            Else

                Console.WriteLine("N Gravou")

            End If

        End If


    End Function



End Class
